# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ae6d902a4d7058a10b606304bc8b9f37f3afdd3158fd40fad3dbd57e735c54ae9135e6b61bc8f1bbefc51182875eda259ee491c42bdde7c290aea8b1d1e3f4d

test:
  secret_key_base: efe4ad64e5d965210ec0f849ea23daa34c9ced0bfa64832d3a053828b5df926bf10c833db55a641d2b1651eebfacb27dd85849c7208b385dd0c6a35e6305b6b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
