  
development: 
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"
  username: "postgres"
  password: "postgres"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"
  
  database: samplee_development
  
  
test: 
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"
  username: "postgres"
  password: "postgres"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"
  
  database: samplee_test
  
  
production: 
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"
  username: "postgres"
  password: "postgres"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>"
  
  database: samplee_production